services:
    marttiphpbb.showphpbbevents.listener:
        class: marttiphpbb\showphpbbevents\event\listener
        arguments:
            - '@request'
            - '@user'
            - '@marttiphpbb.showphpbbevents.service.events_cache'
            - '@marttiphpbb.showphpbbevents.php_event_listener'
        tags:
            - { name: event.listener }

    marttiphpbb.showphpbbevents.php_event_listener:
        class: marttiphpbb\showphpbbevents\event\php_event_listener
        tags:
            - { name: event.listener }

    marttiphpbb.showphpbbevents.service.events_cache:
        class: marttiphpbb\showphpbbevents\service\events_cache
        arguments:
            - '@cache.driver'
            - '@marttiphpbb.showphpbbevents.service.events_store'

    marttiphpbb.showphpbbevents.service.events_store:
        class: marttiphpbb\showphpbbevents\service\events_store

    marttiphpbb.showphpbbevents.console.scrape:
        class: marttiphpbb\showphpbbevents\console\scrape
        arguments:
            - '@user'
            - '@marttiphpbb.showphpbbevents.service.events_cache'
        tags:
            - { name: console.command }

    marttiphpbb.showphpbbevents.console.extract:
        class: marttiphpbb\showphpbbevents\console\extract
        arguments:
            - '@user'
            - '@marttiphpbb.showphpbbevents.service.events_cache'
        tags:
            - { name: console.command }

    marttiphpbb.showphpbbevents.console.verify:
        class: marttiphpbb\showphpbbevents\console\verify
        arguments:
            - '@user'
            - '@marttiphpbb.showphpbbevents.service.events_cache'
        tags:
            - { name: console.command }

    marttiphpbb.showphpbbevents.console.generate:
        class: marttiphpbb\showphpbbevents\console\generate
        arguments:
            - '@user'
            - '@marttiphpbb.showphpbbevents.service.events_store'
        tags:
            - { name: console.command }

    marttiphpbb.showphpbbevents.console.write:
        class: marttiphpbb\showphpbbevents\console\write
        arguments:
            - '@user'
            - '@marttiphpbb.showphpbbevents.service.events_cache'
            - '@marttiphpbb.showphpbbevents.service.events_store'
        tags:
            - { name: console.command }

    marttiphpbb.showphpbbevents.console.show:
        class: marttiphpbb\showphpbbevents\console\show
        arguments:
            - '@user'
            - '@marttiphpbb.showphpbbevents.service.events_cache'
            - '@marttiphpbb.showphpbbevents.service.events_store'
        tags:
            - { name: console.command }
