services:
    marttiphpbb.templateevents.listener:
        class: marttiphpbb\templateevents\event\listener
        arguments:
            - '@request'
        tags:
            - { name: event.listener }

    marttiphpbb.templateevents.php_event_listener:
        class: marttiphpbb\templateevents\event\php_event_listener
        tags:
            - { name: event.listener }            

    marttiphpbb.templateevents.twig.extension:
        class: marttiphpbb\templateevents\twig\extension
        arguments:
            - '@request'
            - '@user'
            - '@language'
            - '@marttiphpbb.templateevents.php_event_listener'
        tags:
            - { name: twig.extension }
            
    marttiphpbb.templateevents.console.scrape:
        class: marttiphpbb\templateevents\console\scrape
        arguments:
            - '@user'
            - '@cache.driver'
        tags:
            - { name: console.command }    

    marttiphpbb.templateevents.console.verify:
        class: marttiphpbb\templateevents\console\verify
        arguments:
            - '@user'
            - '@cache.driver'
        tags:
            - { name: console.command }

    marttiphpbb.templateevents.console.generate_php_listener:
        class: marttiphpbb\templateevents\console\generate_php_listener
        arguments:
            - '@user'
            - '@cache.driver'
        tags:
            - { name: console.command }
